### ISSUE TITLE
How to verify ZTP Test Case#5 ?

### ISSUE THREAD

**Issue by peter-yu** [Azure/sonic-ztp#31]
Hi all,
In (https://github.com/Azure/SONiC/blob/master/doc/ztp/ztp.md#test-case-5)
Test Case \# 5
Objective: Verify support for reboot and resume in the middle of execution of a configuration section in the middle of ZTP process.
Test Steps:
- Use steps defined in Test Case \# 4 to initiate ZTP and perform configuration tasks
- Inside the plugin script of 3rd task, ''03-conf-task', issue a reboot command and let switch restart

Expected Result:
- After reboot ZTP will not execute 01-config-task-1 and 02-conf-task2.
- ZTP executes 03-conf-task and 03-end-step in order
- Result of ZTP is success only if all configuration task's results are success

It seems failed to resume to next configuration section (ex: 04-task) if the script of 3rd task includes a reboot command.
```
#!/bin/bash
echo "this is script_reboot.sh"
exec reboot
exit 0
```
**the symptom is that the plugin status of 3rd task is always "IN-PROGRESS", and the DUT reboots again and again.**
Is the the script of 3rd task is a valid implementation? Or should I use _reboot-on-success_ in ZTP framework to resume to 04-task after rebooting?
Thanks.

**Comment by peter-yu** [comment]
@rajendra-dendukuri Can you give me a suggestion? Thanks.

**Comment by rajendra-dendukuri** [comment]
The test script should conditionally reboot and not always reboot. The point of this test is that the 03-configuration task is resumed after it has rebooted without finishing it. May be something like below

#!/bin/bash
if [ ! -f /home/admin/reboot_initiated ]; then 
    touch /home/admin/reboot_initiated
    echo "this is script_reboot.sh"
    exec reboot
else
    rm -f /home/admin/reboot_initiated
fi
exit 0

**Comment by peter-yu** [comment]
This clarifies my misunderstanding. Thank you.
